### ISSUE TITLE
Update to 2022.3.1 fails (UnicodeEncodeError)

### ISSUE THREAD

**Issue by slepkaviba** [OctoPrint/OctoPrint-PiSupport#8]
While updating update fails with error:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-43: ordinal not in range(256)

Trace from octoprint.log:
octoprint.plugins.softwareupdate - ERROR - Update of pi_support can not be performed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 2089, in _perform_update
    update_result = updater.perform_update(
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 115, in perform_update
    returncode, stdout, stderr = pip_caller.execute(*pip_args, **pip_kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 208, in execute
    return self.call(command, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/commandline.py", line 244, in call
    all_stdout += process_stdout(p.stdout.readlines(timeout=0.5))
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/commandline.py", line 236, in process_stdout
    return process_lines(lines, self._log_stdout)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/commandline.py", line 229, in process_lines
    processed = self._preprocess_lines(
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 498, in _preprocess_lines
    return list(map(self._preprocess, lines))
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 517, in _preprocess
    return to_unicode(clean_ansi(text))
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/commandline.py", line 57, in clean_ansi
    return _ANSI_REGEX.sub(b"", line.encode("latin1")).decode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-43: ordinal not in range(256)

**Comment by foosel** [comment]
Known issue in OctoPrint when run against pip 22+, will be fixed in 1.8.0 which will hopefully be available as a release candidate soon.

Fix is to wait with the update, update on commandline or downgrade pip.

**Comment by slepkaviba** [comment]
Thank you for siwft reply, actually after restart it seems to be in latest version... Does it mean it is updated or reports wrong version?

**Comment by cp2004** [comment]
It updates fine, but OctoPrint fails to tell you that due to the UnicodeDecodeError - after a manual restart the new version is loaded.
