### ISSUE TITLE
[BUG] Unable to update Pi Support Plugin from 2021.10.28 to 2022.3.1

### ISSUE THREAD

**Issue by ntlhui** [OctoPrint/OctoPrint-PiSupport#9]
From `octoprint.log`:
```
2022-03-05 18:39:14,243 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from https://plugins.octoprint.org/plugins.json
2022-03-05 18:39:24,824 - octoprint.plugins.softwareupdate - INFO - Starting update of pi_support to 2022.3.1...
2022-03-05 18:39:33,177 - octoprint.plugins.softwareupdate - ERROR - Update of pi_support can not be performed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 2090, in _perform_update
    target, populated_check, target_version, log_cb=self._log, online=online
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 115, in perform_update
    returncode, stdout, stderr = pip_caller.execute(*pip_args, **pip_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 208, in execute
    return self.call(command, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 244, in call
    all_stdout += process_stdout(p.stdout.readlines(timeout=0.5))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 236, in process_stdout
    return process_lines(lines, self._log_stdout)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 230, in process_lines
    *map(lambda x: to_unicode(x, errors="replace"), lines)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 498, in _preprocess_lines
    return list(map(self._preprocess, lines))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 517, in _preprocess
    return to_unicode(clean_ansi(text))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 57, in clean_ansi
    return _ANSI_REGEX.sub(b"", line.encode("latin1")).decode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-43: ordinal not in range(256)
2022-03-05 18:39:33,267 - octoprint.plugins.softwareupdate - INFO - Saved update log to disk
2022-03-05 18:39:33,790 - octoprint.plugins.tracking - INFO - Sent tracking event update_failed, payload: {'target': 'pi_support', 'from_version': '2021.10.28', 'to_version': '2022.3.1'}
```

From `plugin_softwareupdate_console.log`:
```
2022-03-05 18:32:57,972   /home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/OctoPrint/OctoPrint-PiSupport/archive/2022.3.1.zip --no-cache-dir
2022-03-05 18:33:02,398 > Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2022-03-05 18:33:02,400 > Collecting https://github.com/OctoPrint/OctoPrint-PiSupport/archive/2022.3.1.zip
2022-03-05 18:39:24,838   /home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/OctoPrint/OctoPrint-PiSupport/archive/2022.3.1.zip --no-cache-dir
```

`pip` is 22.0.3
`OctoPrint` is 1.7.3
Pi is a Raspberry Pi 3B+
`uname -a`: `Linux e4e-octopi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux`

**Comment by ntlhui** [comment]
Verified that `pip` on this system still works by installing another plugin, so this is most likely related to the `.zip` file `pip` is trying to grab.

**Comment by kantlivelong** [comment]
See https://github.com/OctoPrint/OctoPrint/issues/4392
